### ISSUE TITLE
403 error code after trying to get my grades

### ISSUE THREAD

**Issue by jktechs** [elisaado/somtoday-api-docs#12]
`testUrl = base+'/rest/v1/resultaten/huidigVoorLeerling/'+str(userId)`
`grades = rq.get(testUrl, headers={'Authorization': 'Bearer '+access_token, 'Accept': 'application/json','Range':'items=5-7'})
print(grades.json());`
this is some python code i am using to test.
i know my base url and token are correct.
the userId is from a request to `/rest/v1/leerlingen`
the json error is `{'code': 403, 'reason': 'Forbidden', 'exception': 'javax.ws.rs.WebApplicationException', 'message': 'HTTP 403 Forbidden', 'applicationErrorParameters': {}}`

**Comment by jktechs** [comment]
I am a total idiot. I thought because I could see my grades in the app I should be able to access them via the api. But i am in the middle of a test week so I can’t see my grades. The grades I saw in the app are cashed

**Comment by elisaado** [comment]
I hope it worked, I'll close the issue for now but you can re-open it if the issue still persists.
