### ISSUE TITLE
405 at logging in

### ISSUE THREAD

**Issue by MakerTim** [elisaado/somtoday-api-docs#2]
Hey,

I try to login with the details you supply here, but i got a 405 method not allowed
could you help me out?
![image](https://user-images.githubusercontent.com/1375359/48259803-7d29b200-e419-11e8-9166-d4219ac87459.png)
![image](https://user-images.githubusercontent.com/1375359/48259825-929edc00-e419-11e8-8f8a-5644ead28127.png)

I think im doing something wrong, but i dont see what

**Comment by elisaado** [comment]
Hello @MakerTim, thank you for reporting this issue. I will try to look into it.

**Comment by MakerTim** [comment]
school_uuid='16b771e9-dd53-4457-a355-ed849c2bfba' username='113990' password='<password>' && curl "https://production.somtoday.nl/oauth2/token" -d "grant_type=password&username=$school_uuid\\$username&password=$password&scope=openid" -H "Authorization: Basic RDUwRTBDMDYtMzJEMS00QjQxLUExMzctQTlBODUwQzg5MkMyOnZEZFdkS3dQTmFQQ3loQ0RoYUNuTmV5ZHlMeFNHTkpY" --silent
![image](https://user-images.githubusercontent.com/1375359/48262234-1230a900-e422-11e8-9739-8022e090a765.png)
still getting invalid_grant, am i doing something wrong here? i copy-pasted it from the readme file

**Comment by MakerTim** [comment]
Okay, im a derp; forgot the last character in the UUID
invalid_grant == invalid credentials
good thing to add in the documentation :)

**Comment by elisaado** [comment]
Yeah, for all methods we should probably add an "error" section. If you have any suggestions, please open a pull request :)
