### ISSUE TITLE
How to get all the grades

### ISSUE THREAD

**Issue by Wolletje01** [elisaado/somtoday-api-docs#22]
How to get all the grades, not only the average but all the grades with the weighting (weging)

**Comment by elisaado** [comment]
Hey @Wolletje01, the method mentioned in the documentation will return all grades. You can also use a library like somtoday.js  to have the library fetch them for you, you can find it at https://github.com/elisaado/somtoday.js

The Github issues are not made for questions like these, I'd advice you to join the discord at https://discord.gg/yE3e3erCut.
