### ISSUE TITLE
{"error_description":"Invalid grant: Account has 2 attempts remaining","error":"invalid_grant"}

### ISSUE THREAD

**Issue by ChielChiel** [elisaado/somtoday-api-docs#6]
Hi, I'm trying to login to somtoday via curl in the terminal. I'm using the following command:
``` zsh
curl "https://production.somtoday.nl/oauth2/token" -d "grant_type=password&username=[school_uuid]\\[username]&password=[password]&scope=openid" -H "Authorization: Basic RDUwRTBDMDYtMzJEMS00QjQxLUExMzctQTlBODUwQzg5MkMyOnZEZFdkS3dQTmFQQ3loQ0RoYUNuTmV5ZHlMeFNHTkpY"

```
With `[xyz]` being filled in (in plain text, no encryption) on my side.

However I keep getting the following error:
``` zsh
{"error_description":"Invalid grant: Account has 2 attempts remaining","error":"invalid_grant"}
```

It keeps saying that I have either 2 or 1 attempts remaining. It doesn't drop below 1. 

How can I make this work?

Thanks,

Michiel

**Comment by elisaado** [comment]
I have experienced that whenever the counter doesn't drop below 1, it is actually that the username is wrong and not the password. Are you sure the username you use is the exact same you use on SOMtoday in the browser?

**Comment by elisaado** [comment]
I have tested the route and it still works for me, so something might be going on on your side.

If you can, try to use `curl -v` instead of just `curl`, it will print the full http request, then you could copy and paste it here so I can analyse it.

Be sure to censor/blur out any of your info/tokens/passwords!

**Comment by ChielChiel** [comment]
Thanks for helping me, after running: 
``` zsh
curl -v "https://production.somtoday.nl/oauth2/token" -d "grant_type=password&username[school_uuid]\\[username]&password=[password]&scope=openid" -H "Authorization: Basic RDUwRTBDMDYtMzJEMS00QjQxLUExMzctQTlBODUwQzg5MkMyOnZEZFdkS3dQTmFQQ3loQ0RoYUNuTmV5ZHlMeFNHTkpY"
```

It gives the following response:
``` zsh
*   Trying 84.241.178.86...
* TCP_NODELAY set
* Connected to production.somtoday.nl (84.241.178.86) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=NL; postalCode=7411 HW; ST=Overijssel; L=Deventer; street=Singel 25; O=Topicus.Education B.V.; OU=Somtoday; OU=Wildcard SSL; CN=*.somtoday.nl
*  start date: Aug 27 00:00:00 2018 GMT
*  expire date: Aug 26 23:59:59 2020 GMT
*  subjectAltName: host "production.somtoday.nl" matched cert's "*.somtoday.nl"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO RSA Organization Validation Secure Server CA
*  SSL certificate verify ok.
> POST /oauth2/token HTTP/1.1
> Host: production.somtoday.nl
> User-Agent: curl/7.64.1
> Accept: */*
> Authorization: Basic RDUwRTBDMDYtMzJEMS00QjQxLUExMzctQTlBODUwQzg5MkMyOnZEZFdkS3dQTmFQQ3loQ0RoYUNuTmV5ZHlMeFNHTkpY
> Content-Length: 113
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 113 out of 113 bytes
< HTTP/1.1 400 Bad Request
< Date: Fri, 05 Jun 2020 15:48:15 GMT
< Server: Apache
< Strict-Transport-Security: max-age=31536000; includeSubdomains
< X-Frame-Options: SAMEORIGIN
< X-Frame-Options: DENY
< Content-Type: application/json
< Content-Length: 95
< X-Robots-Tag: none
< X-UA-Compatible: IE=Edge
< Connection: close
< 
* Closing connection 0
* TLSv1.2 (OUT), TLS alert, close notify (256):
{"error_description":"Invalid grant: Account has 2 attempts remaining","error":"invalid_grant"}% 
```

Hope this can be helpful!

**Comment by elisaado** [comment]
I don't notice anything weird about the request.

Have you checked your username and school uuid to be correct?

**Comment by ChielChiel** [comment]
> I don't notice anything weird about the request.
> 
> Have you checked your username and school uuid to be correct?

Yes I have checked the uuid and username. Do I have to put `"` or `'` around the parameters of the url?

 As you can see in the response, it gives a `HTTP/1.1 400 Bad Request` [bad request](https://www.lifewire.com/how-to-fix-a-400-bad-request-error-2617988). Maybe there's something wrong with the formatting of the request or something. Maybe the headers have changed. Just naming possible options now.

**Comment by ChielChiel** [comment]
@elisaado is there maybe a way you could send your curl string with placeholder values so that i can make sure i don’t have some sort of typo?

**Comment by elisaado** [comment]
Yeah I have noticed the 400 code, but I think this is just SOMtoday misusing their HTTP codes. 

I do believe that I have found your though
`curl -v "https://production.somtoday.nl/oauth2/token" -d "grant_type=password&username[school_uuid]\\[username]&password=[password]&scope=openid" -H "Authorization: Basic RDUwRTBDMDYtMzJEMS00QjQxLUExMzctQTlBODUwQzg5MkMyOnZEZFdkS3dQTmFQQ3loQ0RoYUNuTmV5ZHlMeFNHTkpY"` 

should be
`curl -v "https://production.somtoday.nl/oauth2/token" -d "grant_type=password&username=[school_uuid]\\[username]&password=[password]&scope=openid" -H "Authorization: Basic RDUwRTBDMDYtMzJEMS00QjQxLUExMzctQTlBODUwQzg5MkMyOnZEZFdkS3dQTmFQQ3loQ0RoYUNuTmV5ZHlMeFNHTkpY"`

What did I change?
I changed `&username[....` to `&username=[...`.

**Comment by elisaado** [comment]
I read your original issue and the equals sign is present there. Hmmmmm.

**Comment by elisaado** [comment]
I will send my curl command.

```bash
curl -v "https://production.somtoday.nl/oauth2/token" -d "grant_type=password&username=<my school uuid>\\<my username>&password=<my password>&scope=openid" -H "Authorization: Basic RDUwRTBDMDYtMzJEMS00QjQxLUExMzctQTlBODUwQzg5MkMyOnZEZFdkS3dQTmFQQ3loQ0RoYUNuTmV5ZHlMeFNHTkpY"```

**Comment by elisaado** [comment]
Intentionally typing my password wrong yields a `400 Bad Request` which confirms my previous comment about SOMtoday misusing their HTTP codes.

**Comment by ChielChiel** [comment]
> I will send my curl command.
> 
> ```shell
> curl -v "https://production.somtoday.nl/oauth2/token" -d "grant_type=password&username=<my school uuid>\\<my username>&password=<my password>&scope=openid" -H "Authorization: Basic RDUwRTBDMDYtMzJEMS00QjQxLUExMzctQTlBODUwQzg5MkMyOnZEZFdkS3dQTmFQQ3loQ0RoYUNuTmV5ZHlMeFNHTkpY"
> ```

Unforanetly using this didn't work for me.  Btw, just to be sure, `<my password>` is in plaintext as well? Or should all the parameters be url-formatted first?

Besides my school uses the following `https://login.microsoftonline.com/school.nl/v2.0` url to login. In that login screen there's an option to "remember me". Can it be that because of that user input, it is unable to login?

**Comment by elisaado** [comment]
Strange!

The issue may be because your school uses Microsoft OAuth to log in. I will look into this.

**Comment by elisaado** [comment]
Is the Microsoft login page the only way for you to log in on somtoday.nl?

**Comment by elisaado** [comment]
Yes. The password parameter is sent in plaintext but with SSL to ensure no one could just read it from the HTTP request. curl does that automatically so there should be no problem there.

**Comment by ChielChiel** [comment]
Oké, i see.
I've just checked the login process in a private window. The redirects are as follows:

1. somtoday.nl (choose school and username (but no password))
2. login.microsoftonline.com (redirects immediately to number 3)
3. login.umbrella-organisation.nl (Here I have to manually login with my password and username)
4. login.microsoftonline.com (Here I'm able to opt-in that I want to "Stay signed in")
5. school-elo.somtoday.nl

Yes, it's quite a strange route

**Comment by elisaado** [comment]
My own school does not use this new authentication method so I am not sure how to use it.

**Comment by ChielChiel** [comment]
Oke i see. Where did you get the api endpoints from? Maybe ill be able to find some more information there...

**Comment by elisaado** [comment]
I get them from https://servers.somtoday.nl/organisaties.json

**Comment by elisaado** [comment]
I built up the entire documentation by two methods
- decompiling the app and analysing its code
- proxying the app through my PC to analyse the requests made by the app

The headers you mentioned are used by web-browsers to determine if a website allows to be embedded inside an <iframe> component, sadly they have nothing to do with authentication.

**Comment by elisaado** [comment]
> Could it be that these options prevent me from login without using gui?

Your school uses SSO authentication which means the authentication is not going through SOMtoday but through a third-party OAuth provider (microsoft in our case). It's not really about using a GUI or not, it's about authenticating through SOM, which you can't do.

What we need to do: find a way to authenticate through Microsoft and provide the instructions for that in this documentation

**Comment by ChielChiel** [comment]
Right, i would be happy to help!
Maybe we could try something like this: 
(Microsofts login which returns a bearer token)[ https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow]

**Comment by ChielChiel** [comment]
What would the accesstoken look like? As in length or type of characters?

**Comment by elisaado** [comment]
The SOMtoday access token looks something like this:
```eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI4YjMwYTdmMC1jN2I3LTQ3NDMtOWE4ZC1kNTlhMDE5YWY3NDkiLCJzdWIiOiJkMjhiOTQ1My0zYzY4LTQxYWQtOGI2Yy1hNTM0NTM4M2UwYzIiLCJpYXQiOjE0ODIxODU5NTAsImV4cCI6MTQ4MjE4OTU1MCwiYXVkIjpbInN5bWJvbHMiLCJvaGxjIiwiZmVlZCIsImNyb3NzcmF0ZXMiXX0.ZlKvCDKnwAjsS0KIZ5gAHcbaw6MFWKwSDcchjdIGPqg``` 

It's called a JSON Web Token (JWT)

**Comment by elisaado** [comment]
I have recently used a proxy to look at the request the SOMToday app is making, this means that I can try to document the SSO Authentication flow, but for this I would need the school, username and password of a user that uses SSO authentication (like you).

Giving your password over the internet is however _very_ sketchy, so I am still thinking whether or not I should do it.

**Comment by ChielChiel** [comment]
> I have recently used a proxy to look at the request the SOMToday app is making, this means that I can try to document the SSO Authentication flow, but for this I would need the school, username and password of a user that uses SSO authentication (like you).
> 
> Giving your password over the internet is however _very_ sketchy, so I am still thinking whether or not I should do it.

Yeah, well I'm not comfortable with giving you my credentials since they are linked to my google drive as well. However, I can try to create a proxy just like you did and show you the requests that are made. However I have never done or tried anything like that before.

**Comment by ChielChiel** [comment]
Oke when I retrieve the presumed bearer token from normal (gui) login and run the following command: `curl -v "https://greijdanus-api.somtoday.nl/rest/v1/leerlingen" -H "Authorization: Bearer eyJ4NXQjUzI1NiI6ImxZZ2VJNnNQMDY1Um1QTlloZ1dZcmNYcElTNWpidEM5X3V3Z0p0WV8xQVkiLCJraWQiOiJpcmlkaXVtaWRwLTYyNTQ5NDg3Mjc1MzI2NTQwNTcxNDc0NDAzNzAyMzE3NDQ4NTU3IiwiYWxnIjoiUlMyNTYifQ.eyJtZXRob2QiOiJwd2QiLCJhdXRoVGltZSI6IjIwMjAtMDYtMDdUMTY6NTk6MTEuMjQ5WiIsImV4cCI6MTU5MTU1Mjc1MSwicGFyYW1ldGVycyI6eyJ0ZW5hbnRfdXVpZCI6ImNiZWFiNjU4LWM5ZTYtNGE1NC1iNDE5LThmNjgyZjgyZWE1NCJ9fQ.Iq1By0eX4Mlf7ZYMEQRw3KzYa5HKKAoyWjTKa8IaC0vd8gNbSutH76DDnp4tOWnt9sOkEP6lDerKwr3Yetrv13YiuIZPFQG7KgjDmpc94si5OyNROGkDKzfY1_FByxNlGT2Q0fevw1eH14zfUxcxlfonRX2SOAYoQ-AHysuEmyj611QQznmt8WNVXLRBav9MVdcJndUglgL92zDHEETGBTuJVvpj-3iG5DAatR7-jwCYII_snlp91WJBK2NiIq5MIxPXSKWbzZedc6KolcCaMWloNLU9VSLqpPq0CBfqlFm3Q5GgeA5_CbwnwfzaHofELbFV2GNekKlyBSkgARwf9A" -H "Accept: application/json" -A "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36"`

It returns the following:
``` zsh
*   Trying 84.241.178.86...
* TCP_NODELAY set
* Connected to greijdanus-api.somtoday.nl (84.241.178.86) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=NL; postalCode=7411 HW; ST=Overijssel; L=Deventer; street=Singel 25; O=Topicus.Education B.V.; OU=Somtoday; OU=Wildcard SSL; CN=*.somtoday.nl
*  start date: Aug 27 00:00:00 2018 GMT
*  expire date: Aug 26 23:59:59 2020 GMT
*  subjectAltName: host "greijdanus-api.somtoday.nl" matched cert's "*.somtoday.nl"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO RSA Organization Validation Secure Server CA
*  SSL certificate verify ok.
> GET /rest/v1/leerlingen HTTP/1.1
> Host: greijdanus-api.somtoday.nl
> User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36
> Authorization: Bearer eyJ4NXQjUzI1NiI6ImxZZ2VJNnNQMDY1Um1QTlloZ1dZcmNYcElTNWpidEM5X3V3Z0p0WV8xQVkiLCJraWQiOiJpcmlkaXVtaWRwLTYyNTQ5NDg3Mjc1MzI2NTQwNTcxNDc0NDAzNzAyMzE3NDQ4NTU3IiwiYWxnIjoiUlMyNTYifQ.eyJtZXRob2QiOiJwd2QiLCJhdXRoVGltZSI6IjIwMjAtMDYtMDdUMTY6NTk6MTEuMjQ5WiIsImV4cCI6MTU5MTU1Mjc1MSwicGFyYW1ldGVycyI6eyJ0ZW5hbnRfdXVpZCI6ImNiZWFiNjU4LWM5ZTYtNGE1NC1iNDE5LThmNjgyZjgyZWE1NCJ9fQ.Iq1By0eX4Mlf7ZYMEQRw3KzYa5HKKAoyWjTKa8IaC0vd8gNbSutH76DDnp4tOWnt9sOkEP6lDerKwr3Yetrv13YiuIZPFQG7KgjDmpc94si5OyNROGkDKzfY1_FByxNlGT2Q0fevw1eH14zfUxcxlfonRX2SOAYoQ-AHysuEmyj611QQznmt8WNVXLRBav9MVdcJndUglgL92zDHEETGBTuJVvpj-3iG5DAatR7-jwCYII_snlp91WJBK2NiIq5MIxPXSKWbzZedc6KolcCaMWloNLU9VSLqpPq0CBfqlFm3Q5GgeA5_CbwnwfzaHofELbFV2GNekKlyBSkgARwf9A
> Accept: application/json
> 
< HTTP/1.1 401 Unauthorized
< Date: Sun, 07 Jun 2020 17:09:16 GMT
< Server: Apache
< Strict-Transport-Security: max-age=31536000; includeSubdomains
< X-Frame-Options: SAMEORIGIN
< Access-Control-Allow-Origin: *
< WWW-Authenticate: Bearer
< Access-Control-Allow-Headers: Range, Authorization, content-type, Content-Range
< Access-Control-Expose-Headers: Content-Range
< Content-Length: 0
< Access-Control-Allow-Methods: GET, POST, PUT, OPTIONS, DELETE, HEAD
< X-Robots-Tag: none
< X-UA-Compatible: IE=Edge
< 
* Connection #0 to host greijdanus-api.somtoday.nl left intact
* Closing connection 0
```

But no json as you can see. What am I missing?

**Comment by elisaado** [comment]
How did you get this token if I may ask?
The SOMToday website gives you the IDToken, not the access token sadly.

**Comment by elisaado** [comment]
In some apps, the idtoken can be used as the bearer access token, but that doesn't seem to work in SOMToday.

**Comment by ChielChiel** [comment]
Well i got this token from the landing page of somtoday. When one is signed off en goes to (somtoday.nl) an auth key is added to the url: ‘https://somtoday.nl/?auth=eyJ4NXQjUzI1NiI6ImxZZ2VJNnNQMDY1Um1QTlloZ1dZcmNYcElTNWpidEM5X3V3Z0p0WV8xQVkiLCJraWQiOiJpcmlkaXVtaWRwLTYyNTQ5NDg3Mjc1MzI2NTQwNTcxNDc0NDAzNzAyMzE3NDQ4NTU3IiwiYWxnIjoiUlMyNTYifQ.eyJtZXRob2QiOiJwd2QiLCJhdXRoVGltZSI6IjIwMjAtMDYtMDhUMDg6NDk6MzAuMDY5WiIsImV4cCI6MTU5MTYwOTc3MCwicGFyYW1ldGVycyI6eyJ1c2VybmFtZSI6IjE3NjE4In19.SFOSZbZzHidaAhRf_exrjBVuKZSjZI4AGXWfEz-2aLqCLQdWsrAzlCSRJvdCC3VsmBHwL55lRilzkyoLR45g4RbtUKgkobypZ1uA-Vg8lzOFTY12IJkr863x6qadYINBKOnpVMpmXDmHoPJBcJX1niSzQA2nuPYa8jPOQdD4kLluFG4Bw4BHSTd2vCLIgnU4a-PlLBucga2gcRO5AeC9-guEiEYGqt3L913X4wd-1-kqnsbEdV2ZXglNyoBDhddAc7cUj0m5L0wyhRd_TIKrI1QYykVAsnNwiVDVS1xP4K7Bd6fmvwxj_rs_xA8gr6vOvj83BAvYKiTqbc7wElsluA’

**Comment by elisaado** [comment]
I have checked and I get the same ?auth= token, but it is unusable for me too.

**Comment by elisaado** [comment]
When you log in via the app and pick Greijdanus, it doesn't redirect to the oauth provider instantly, could you try logging in from there and see what happens? (without tapping "Inloggen via Single Sign On")

**Comment by ChielChiel** [comment]
Well when I tap "Inloggen via Somtoday" it just creates a new webview with the standard Somtoday login screen, as if you would open somtoday.nl on your mobile browser.

**Comment by elisaado** [comment]
interesting!

**Comment by elisaado** [comment]
I am coming very close to imitating the app's behavior via cURL, but I am still clueless on a couple of things.

**Comment by ChielChiel** [comment]
Okay, great to hear! Could you maybe give a small update on the things you are "clueless" about? Maybe I could be of help

**Comment by elisaado** [comment]
Yep

**Comment by elisaado** [comment]
It seems to me that JSESSIONID and idtoken store something about the state of authentication

**Comment by elisaado** [comment]
the IDToken is not constant, it changes even when picking the same school which suggests it's used as for example a CSRF token

**Comment by ChielChiel** [comment]
> the IDToken is not constant, it changes even when picking the same school which suggests it's used as for example a CSRF token

Do you mean all of the contents or just the encrypted version? Because `1592061457` is just epoch time translating to this 13-06 17:17. So maybe this states how long until the token should be refreshed.

Btw, didn't you have a valid access_token? Probably sounds stupid but isn't there a way we could recreate that token synthetically, without actually loggin in?

**Comment by elisaado** [comment]
Closing as #7 is the continuation of this issue.
